<SCRIPT language=JavaScript src="lnkbtns/journalvouchers.js" type=text/javascript></SCRIPT>
<SCRIPT language=JavaScript src="cfls/chartofaccounts.js" type=text/javascript></SCRIPT>
<SCRIPT language=JavaScript src="cfls/items.js" type=text/javascript></SCRIPT>
<SCRIPT language=JavaScript src="cfls/profitcenterdistributionrules.js" type=text/javascript></SCRIPT>
<SCRIPT language=JavaScript src="cfls/projects.js" type=text/javascript></SCRIPT>
<SCRIPT language=JavaScript src="cfls/employees.js" type=text/javascript></SCRIPT>
<SCRIPT language=JavaScript src="ajax/xmlvalidatechartofaccounts.js" type=text/javascript></SCRIPT>
<SCRIPT language=JavaScript src="ajax/xmlvalidateitems.js" type=text/javascript></SCRIPT>
<SCRIPT language=JavaScript src="ajax/xmlvalidateprofitcenterdistributionrules.js" type=text/javascript></SCRIPT>
<SCRIPT language=JavaScript src="ajax/xmlvalidateprojects.js" type=text/javascript></SCRIPT>
<SCRIPT language=JavaScript src="ajax/xmlvalidateemployees.js" type=text/javascript></SCRIPT>
